### ISSUE TITLE
Initial Steps before Approach 

### ISSUE THREAD

**Issue by JordanMartinez** [chexxor/purescript-documentation-discussion#1]
Thanks again for setting this up and doing some initial research

So, here's my general thoughts on how we should continue approaching this stuff.

First, I think we should split up the methodology's steps into separate files. If these files get big, it'll be easier to manage them and refer to various sections within them. Who knows? Maybe we'll even use folders for each step at some point in the future, but let's only scale to that size when we need to.

Second, let's add what we currently know/believe to be true about each step. There are likely things we are going to need to do regardless of what conclusions we make. (For example, documenting core libraries) Let's add them in now before we forget about them. Later on, when we go through each step top-down, we can then remove anything that doesn't seem to fit there.

Third, I'm going to better define what I mean by each step to insure we are understanding and using the same terminology.

Fourth, we'll start at the topmost step and go from there.

**Comment by chexxor** [comment]
I'm not sure what you mean, concretely, by the second point. Did you include this in the your first PR? If so, that would educate me your meaning.

**Comment by chexxor** [comment]
Ah, perhaps this commit is what you meant: https://github.com/chexxor/purescript-documentation-discussion/commit/12f89a5f81e186996af111c887b4e409e8aa1e88

**Comment by chexxor** [comment]
How do incorporate Ideas-Storage into this process? I agree that there are multiple aspects to this project, so managing them should be something to define here. For example, there might actually be multiple problems we want to solve here, and which strategy do we focus on when solving a problem.

**Comment by JordanMartinez** [comment]
It's meant to just store some ideas we want to recall for later. I don't want to forget what someone has said, so I'm putting it there.
Hmm.... Then again, that purpose might be better fulfilled by using issues to track it that rather than putting it into the project files itself...

**Comment by chexxor** [comment]
Here's an item in Ideas-Storage: "The core libraries' documentation needs to be improved."'

Is this meant to affect *what* we approach with this project? If so, do we need to replicate this project for each of thing we want to approach? One for library docs, one for language tutorial docs, one for language reference docs, etc.?

**Comment by JordanMartinez** [comment]
Oh, let me clarify. Someone suggested that the core libraries are not well documented. I think that is something we will likely consider in the future as to _what_ we actually do for some goal we will later define. So, I wanted to include that here so I wouldn't forget about it.

It's not meant to affect _what_ plans we make in this project for how to fix the documentation issue. It's meant to store that idea, so that after we have defined the context and figured out the purpose and principles, we might look at it and say, "Now that we have a much better understanding of what's going on in the PureScript community, we think this is not an issue anymore." 
Or perhaps when we reach that point, we will instead say, "Ah yes, we remember this idea. We think it's still true. So, why don't we create an outcome like 'By Dec 2019, all functions in core libraries have a small explanation on what the function does, 2-3 examples or counterexamples of how to use that function, and links to other reading material on it if it is advanced.'"

Perhaps this is actually going against the methodology described here and we should remove that file.

**Comment by chexxor** [comment]
After looking through some of these sources, I am starting to see several key "action items", or milestones/sub-projects for this project. I'm excited for the "Purpose", "Principles", and "Outcome" steps of this process, as we'll have some solid answers for those. Perhaps when we work on those steps will be a good time to process the "Idea-Storage" page.

**Comment by JordanMartinez** [comment]
Yup! That's my thinking exactly sir!

Also, we'll be able to define a very clear vision that will help multiple people coordinate their efforts

**Comment by chexxor** [comment]
One thing I'm curious about: Does the "Presuppositions" for this project include a comparison to other programming languages? I've been occasionally looking into other languages and their documentation projects and organization to get a feel for their state, and I'm wondering the stage at which to include my research results into this project. Would this be at the "Brainstorm" and "Next Actions" stage?

**Comment by JordanMartinez** [comment]
Let me clarify what I mean by "Presuppositions." Many people just assume that sources of data are inherently true. When someone comes and tells me that Bobby is a jerk, my first inclination is to assume that that person is actually telling the truth. I presuppose the accuracy of that source of knowledge. However, it might be that the person has had a very bad day where many bad things have happened, one after another. Thus, when Bobby does something quite small, it's the "final straw" for the person and they use harsher language to describe Bobby's action. Thus, I say that we "presuppose" authorities are accurate as a way to make explicit that implicit idea. That's why I changed the "authorities" term into "sources" and clarified that in its definition.

Returning to your question, I think that should be included if we have the manpower for it. While we can look at other language's documentation and take the best of all worlds, we should not be so influenced that we feel we must copy someone else unless there are good logical reasons for doing so (i.e. the paradigm the documentation team took is the best paradigm).

> I'm wondering the stage at which to include my research results into this project. Would this be at the "Brainstorm" and "Next Actions" stage?

That's hard to say. On one hand, if it does go in the brainstorm/brainwrite stage, it might be too low in the thought process. In other words, we might assume unwise things that those language's approaches did not assume and thus they reached a better outcome than we will. For example, Rust has an automation bot that can do a lot of work for them. We might never consider that idea if it's too low in the thought process.
On the other hand, if it's too high-up in the thought process, we might be too heavily influenced by them, such that we do not consider what else could be done besides what has already been done. We might fall prey to thinking that something can only be done in one way. This falls on the other extreme of things.

So, I think we should be aware of what they do, but first be very informed about the PureScript language's context as a whole before considering them. If anything, put it in the 'idea-storage' file so that way you don't forget any cool/crazy ideas you have now.

**Comment by chexxor** [comment]
That makes sense.

I thought of another way of framing this goals of this project to make it easier to answer my question. This project is about **PureScript** and its documentation needs. Right now we are establishing the **needs** of its documentation state. A few steps after that, we will have concrete ways of improving the documentation state. When forming strategies of improving PureScript's documentation state, we can look at other language projects for ideas. Ideas gathered from *other* projects will need to be qualified with their resources and starting point when choosing to adapt that outside idea for this project's use.

I'll make a note in that idea page.

**Comment by JordanMartinez** [comment]
Yup! That's a good way to summarize it.

**Comment by JordanMartinez** [comment]
I think this issue is worth closing, too.
