### ISSUE TITLE
Change the Source's terms and definition file into a ReadMe file for its corresponding folder

### ISSUE THREAD

**Issue by JordanMartinez** [chexxor/purescript-documentation-discussion#10]
Two things here:
- Since we agreed upon #8, there is a file with info that is separated from the folder that includes such info. If we move that file into its folder and rename it to "ReadMe.md" then it will be rendered on GH when one looks at that folder.
- Rather than leaving #6 open, we could add it to the above ReadMe.md file as a way to explain what the formatting is used across the sources there.

**Comment by chexxor** [comment]
Yeah, that's a great idea. This would imply not merging all these separate "source" files back into one big one at the end, which is what I thought the plan was. But I think leaving them as separate files is good too.
I think having a single file will be useful, as it will be easier to reference later. I think we'll only need to reference our interpretations of the sources, so if we create a single file, it can be one which summarizes the contents of the directory and just summarizes the interpretations of all sources or each source.

**Comment by chexxor** [comment]
I'll leave it to you to move that file and add #6 to it, because you initially created that file format.

**Comment by JordanMartinez** [comment]
> if we create a single file, it can be one which summarizes the contents of the directory and just summarizes the interpretations of all sources or each source.

I like that idea. 

Ok. I'll add that in after I finish my current work.

**Comment by JordanMartinez** [comment]
Done.
