### ISSUE TITLE
Payment Wall: Vue-HN

### ISSUE THREAD

**Issue by JordanMartinez** [chexxor/purescript-documentation-discussion#13]
When doing #12, https://vue-hn.now.sh/item/17125882 required a subscript I did not have. This creates two issues:
- No one can see this without a subscription, so perhaps we should just refer to it and say what we concluded based on that. Unfortunately, this means our interpretation process is not as transparent and so maybe people could accuse us of bias
- We shouldn't copy-and-paste their content as that might hit copyright issues

**Comment by chexxor** [comment]
Looks like that was an alternative link to the post originally hosted by hacker news. I fixed the link in https://github.com/chexxor/purescript-documentation-discussion/commit/d95ed5026082f8f69be80f152251282913e33582

Thanks for posting about this problem.
