### ISSUE TITLE
Include date of source in file name

### ISSUE THREAD

**Issue by JordanMartinez** [chexxor/purescript-documentation-discussion#16]
Since our sources are from a large period of time, we can see how one person said/thought X, then said/thought Y (which is now slightly different from X), and then said/thought Z (very different from X). This progression of thought should be reflected in our analysis of things.

So, perhaps we should include the date in a file's name, so that we can easily sort it by date later? This might also count against the idea of #14

**Comment by chexxor** [comment]
Good idea. I think this depends on the results of our Source project. If we discover the same people expressed opinions on this topic at different points in time, the perhaps we should aggregate by person before combining into categories. One benefit of this is that it would make especially "noisy" people from carrying too much weight in this investigation.

**Comment by JordanMartinez** [comment]
> If we discover the same people expressed opinions on this topic at different points in time, the perhaps we should aggregate by person before combining into categories. One benefit of this is that it would make especially "noisy" people from carrying too much weight in this investigation.

Mm... I hadn't thought of the issue of "noisy" people/sources carrying too much weight. That's definitely something we need to be cautious of.

I think we should hold off on making decisions as to how we will combine all our data into a context/narrative until we hit that point. I think I also say this because I'm not entirely sure how/why we would "aggregate by person before combining into categories."

**Comment by chexxor** [comment]
> So, perhaps we should include the date in a file's name, so that we can easily sort it by date later? This might also count against the idea of #14

An idea: We could use the Index.md file (https://github.com/chexxor/purescript-documentation-discussion/issues/24) as a place to keep the date.

**Comment by JordanMartinez** [comment]
That makes more sense and is more flexible.

**Comment by chexxor** [comment]
I added a date column to https://github.com/chexxor/purescript-documentation-discussion/pull/26. I think we can wait to close this issue until we're pretty confident that index file correctly reflects all the files in the sources directory.

**Comment by JordanMartinez** [comment]
Ok. Sounds good!

**Comment by JordanMartinez** [comment]
So, the index file has now been updated to include all sources in 72315435e0bcd8452535ce07d5c79203319bce7b
