### ISSUE TITLE
Analyze 'What nobody tells you about documentation'

### ISSUE THREAD

**Issue by JordanMartinez** [chexxor/purescript-documentation-discussion#18]
https://www.divio.com/blog/documentation/

**Comment by JordanMartinez** [comment]
So... this source is so well-written, that I don't even know what 'interpretation's to write....

**Comment by chexxor** [comment]
I quite like that source's opinions. It's well reasoned and offers concrete suggestions for organization of your own documentation project.

Note that in https://github.com/chexxor/purescript-documentation-discussion/issues/21#issuecomment-455028086 I added to the project's goal that we should evaluate what a "good" documentation website would look like. This source would be a good one towards that goal, if you'd agree we should include that goal.

I realize now that we should add a goal of something like "what aspects a documentation project would have that encourages contributions from readers and maintainers of its underlying project".

**Comment by JordanMartinez** [comment]
> Note that in #21 (comment) I added to the project's goal that we should evaluate what a "good" documentation website would look like. This source would be a good one towards that goal, if you'd agree we should include that goal.

I agree. Part of documentation is not only what gets written/created but also how it is presented.

**Comment by JordanMartinez** [comment]
I think I'll just leave this source as is and put it into the "Done" folder. There doesn't seem to be much to analyze/interpret. Rather, we can just use it's ideas to help put something together in the Context/Narrative phase.

**Comment by chexxor** [comment]
Yeah, that's a good idea. It's a really dense document. If we copy its digested form here, I guess it'll look pretty similar to the source itself. I think you can close this issue, completing that one.

**Comment by JordanMartinez** [comment]
Ok. Sounds good to me.

**Comment by JordanMartinez** [comment]
Closed by 910f6b9
