### ISSUE TITLE
Post our likely 'work hours'?

### ISSUE THREAD

**Issue by JordanMartinez** [chexxor/purescript-documentation-discussion#20]
Just throwing this out there as a thought.

It might be good to indicate which days and when on those days you and I will likely be working on this project. I have sometimes looked at this repo and wondered, "Has Alex done anything since I last checked?" If I see you working on it, I'll be further motivated. In addition, it'll be interesting to read what other thoughts/comments you added to sources that I might not have thought of. Not knowing your schedule, it's hard to know whether I should check. I wonder whether you've done/thought something similar.
Also, since we're keeping communication public, it makes it easier to discuss and fix problems that arise. There might be some kinds of work that are easier to resolve/do when both of us are available and other kinds of work that is best done individually on our own time.

My only concern with this is that you or I might not want to indicate when we're available due to privacy concerns.

**Comment by chexxor** [comment]
Yeah I've seen you making progress on it and I've wanted to do the same. I've had events to attend after work the last two nights, which is uncommon because my only regular after work commitments is Mondays. Well, actually from now it'll be twice a month Tuesday evenings I'll be busy because I've added another once monthly event, but February's meeting will likely be a different day, so... Yeah.

I'll post an update again here in a bit.

**Comment by JordanMartinez** [comment]
:smile: Thanks for the update. I'm not sure what those activities/events are, but I hope they're enjoyable!

**Comment by chexxor** [comment]
I'll plan to contribute to this project about 2-3 days between M-F. I'd like to contribute here on Saturday and Sunday for parts of those days, but I often get pulled into family events on the weekends so I hope you don't get disappointed if I don't make large progress on those days.

**Comment by chexxor** [comment]
I've got a few other projects I'm part of: local Haskell meetup (which I've been neglecting to contribute to in the last several months), planning a podcast (which is going slower than I'd like), working through a category theory book with a local study group, reading some philosophy of mathematics books, and movie & tv diversions. *sigh* I can never make as much progress in any one of these as I'd like.

**Comment by JordanMartinez** [comment]
> I often get pulled into family events on the weekends so I hope you don't get disappointed if I don't make large progress on those days.

Family is more important. I won't be disappointed, and, if they arise, don't entertain guilty thoughts for spending time with them instead of contributing to this.

I'll likely contribute at various times over the week. Due to my commitment (below), I may contribute more time on one week than on another:
- on M,T,R sometime after 6?
- on W/F, sometime throughout the whole day
- on Sat, sometime throughout the whole day
- on Sun, I don't work

My other commitments are my job (unfortunately, only part-time right now), the purescript-reference work, books I'm reading, and spending time with family and friends.

> I've got a few other projects I'm part of: local Haskell meetup (which I've been neglecting to contribute to in the last several months), planning a podcast (which is going slower than I'd like), working through a category theory book with a local study group, reading some philosophy of mathematics books, and movie & tv diversions. sigh I can never make as much progress in any one of these as I'd like.

Sounds like a case of overcommitment (I wonder how much I do that, haha!). It seems to me that you'll have to drop one of those if you want to make more progress.

**Comment by JordanMartinez** [comment]
I think this issue is closed now. If you think otherwise, reopen it.
