### ISSUE TITLE
Clarify outcome of 'gather and interpret sources' phase.

### ISSUE THREAD

**Issue by JordanMartinez** [chexxor/purescript-documentation-discussion#21]
While we're applying a variant of the GTD methdology for this entire project, we're not applying that methodology to our current work. Based on the kind of work we are doing right now, here's how I'd fill in that framework/methodology for this "gather and interpret sources" step. Along the way, I'll include some issues I currently see:
<hr>

Source
- My thoughts / gut feeling

Context
- Having the goal of improving PureScript's documentation, we have biases, ideas, and opinions as to how the documentation could improve. However, we do not have much data backing up these ideas/opinions. Thus, we could be entirely wrong in our thoughts, and so strive towards the wrong goals or do so in the wrong way. 
- We do not yet know about other things that people have done or ideas that others have had as to how things could improve. Thus, we don't need to reinvent the wheel: if we can find such ideas and they are still useful/practical/correct, we should reuse them.
- There might be others who have already tried this and succeeded/failed. We can still learn from their mistakes and success stories.

Purpose
- to reduce our overall biases and subjective notions with more data and evidence to support any future decisions we make
- to be informed by the past, so that we do not repeat the same mistakes as those before us did and so we reuse ideas that already work

Principles
- consider a broad range of types of sources (blog posts, forums, tweets, articles, etc.)
- consider both sources that both support and argue against PureScript as a whole with the emphasis being on its documentation and new-learner-friendliness

(Are there any other principles by which we should abide?)

Outcome
- `undefined` - we haven't specified at what point we will stop gathering/analyzing sources and move on to the next phase. However, my current understanding of this is, "All contributors feel that we have gathered and understood enough sources that we are ready to move on to the next phase (Context / Narrative)." This definition is poorly defined because it's not measurable. Should we at least get 10 sources? Should we have sources that at least cover these topics (user friendliness, common issues with FP, etc.?) Thus, I think this needs to be clarified. 

(Perhaps we could not define this outcome clearly yet because we needed to analyze a few sources to get ideas for what else to search for and analyze.)

Brainwrite
- (9) `undefined` - we don't know what the 'last step' is here or the steps that lead up to this point
- (4) `undefined` - any other steps we need to do before hitting the last one.
- (3) One contributor has finished reviewing the other's analysis of a source. - This seems problematic because it may lead to 'group think.' If one of us reads an already-analyzed source, we see both the source itself and the contributor's analysis. Ideally, we should see only the source and make our own analysis before seeing the other contributor's analysis. Unfortunately, this comes with more work for both of us, so I'm not sure whether we would want to do that.
- (2) One contributor analyzes a source of data by writing their interpretations of it. Unfortunately, we're not doing any sort of categorization of our interpretations, so that it'll be easier to put interpretations for one topic in one group (e.g. "Dependency Manager"-related things)
- (1) Either contributor finds a new source, opens an issue for it so that it can be analyzed later.

Next Actions
- Analyze/Review current sources
- Find/Add new sources

Already done
- Decided upon a workflow to reduce issues that can arise due to distributive nature of our work (#2, #3, #6, #7, #8)
- Decided upon a general idea as to what sources to gather (#9)
<hr>

**Comment by chexxor** [comment]
Good point and good exploration of this already. Thanks for leaving some for me to help with!
What do you think about my additions?

Purpose

- to reduce our overall biases and subjective notions by carefully analyzing evidence related to the the purpose of the overall project, which is to support development of a plan to improve PureScript documentation and friendliness to new-comers
- to be informed by the past, so that we do not repeat the same mistakes as those before us did and so we reuse ideas that already work
- to discover examples of languages with effective documentation which can serve as role models and sources of ideas for the goal of the over-arching project

Principles

- consider a broad range of types of sources (blog posts, forums, tweets, articles, etc.)
- consider *all* sources, no matter they are positive or negative sentiments towards the goal of the over-arching project

Outcome: 

- All contributors have gathered and understood as many sources of knowledge about PureScript's documentation and new-comer-friendliness as can be discovered in the allotted time. The allotted time will be 1-2 weeks of part-time work. Sources should be those uncovered by searching websites which contain terms which are indicative of facts useful to the over-arching goal of the project. Unsure the right place to generate these search terms, but here's a start:
    - PureScript experience (neutral term)
    - PureScript impressions (neutral term)
    - PureScript learning (neutral term)
    - PureScript documentation or docs (neutral term)
    - PureScript community (neutral term)
    - PureScript confusing (negative term)
    - PureScript hard or difficult (negative term)
    - PureScript good or great (positive term)
    - PureScript ?what else?(positive term)
    - language great documentation (positive term)
    - language bad documentation (negative term)

- Analyze sources to clarify the evidence to produce something closer to facts. Keep in mind that the facts will be used by people for the purpose of the over-arching project

**Comment by chexxor** [comment]
Another goal I just now thought of:
What are aspects of a documentation project that would encourage contributions from readers and maintainers of its underlying project.

**Comment by chexxor** [comment]
> Ideally, we should see only the source and make our own analysis before seeing the other contributor's analysis. Unfortunately, this comes with more work for both of us, so I'm not sure whether we would want to do that

That's a good idea. When we decided to both analyze the same sources, I wondered how that would work, and what would be the differing responsibilities/outcomes of each analysis pass. I very much like your analysis because it's quite thorough, and I don't think I can improve on it. I would certainly like to read through your analysis to double-check it, of course, and to learn from your style of analysis to apply to my own analysis.

If we don't double-work sources too much, we can instead spend that time searching for more sources and analyzing them. This would allow us to collect more data.

What are your thoughts on this practice?

**Comment by JordanMartinez** [comment]
> to discover examples of languages with effective documentation which can serve as role models and sources of ideas for the goal of the over-arching project

Excellent purpose statement!

> consider _all_ sources, no matter they are positive or negative sentiments towards the goal of the over-arching project

Yes, that states it much better than mine did.

> All contributors have gathered and understood as many sources of knowledge about PureScript's documentation and new-comer-friendliness as can be discovered in the allotted time. The allotted time will be 1-2 weeks of part-time work.

I think the 1-2 week time period is reasonable as an initial idea. We would eventually like to start improving the documentation ;-) Still, I'm not sure what we will uncover in that time period where it might make more sense to continue searching. So, how about we plan on that being the case (1-2 time period) unless we come across something that we both agree should mean we continue searching for info?

> Sources should be those uncovered by searching websites which contain terms which are indicative of facts useful to the over-arching goal of the project. Unsure the right place to generate these search terms, but here's a start....

I think those a good search terms. It's hard to know, tbh.

> Analyze sources to clarify the evidence to produce something closer to facts. Keep in mind that the facts will be used by people for the purpose of the over-arching project

The way this is worded makes it sound more like an action we will eventually do. If it was stated in a past tense sort of way, then it would seem better:
"All sources have been analyzed in such a way that the evidence to produce something closer to facts is apparent."

**Comment by JordanMartinez** [comment]
> Another goal I just now thought of:
> What are aspects of a documentation project that would encourage contributions from readers and maintainers of its underlying project.

Good idea! Let's include that in the 'idea storage' file for now and come back to it later.

An idea for how we could possibly make that true: it might help if there was a sort of 'template file' that people could copy and paste into a library that provides the necessary structure, and then that author fills out its contents with library-specific info. Perhaps this template could be used throughout the ecosystem and make it easier for authors to write it and for people to read it?

**Comment by JordanMartinez** [comment]
> That's a good idea. When we decided to both analyze the same sources, I wondered how that would work, and what would be the differing responsibilities/outcomes of each analysis pass. I very much like your analysis because it's quite thorough, and I don't think I can improve on it. I would certainly like to read through your analysis to double-check it, of course, and to learn from your style of analysis to apply to my own analysis.
> If we don't double-work sources too much, we can instead spend that time searching for more sources and analyzing them. This would allow us to collect more data.
> What are your thoughts on this practice?

Related to #20, it seems you are more limited by time than I am right now. When this project first began, you had already found a number of sources. I've had more time to analyze them and if you think I've done a thorough job, perhaps we should keep those roles? In other words, perhaps you should use your more limited time to gather sources that I, with more time, can thoroughly analyze, and which you can later review and add your own thoughts/comments? Then, I think we as a team could accomplish a good amount even in a short time period like 1-2 weeks.

**Comment by JordanMartinez** [comment]
> Sources should be those uncovered by searching websites which contain terms which are indicative of facts useful to the over-arching goal of the project.

Looking at this again, this is more of a 'brainwrite' idea for how we could accomplish the goal: only use search engines to find written ideas about PS' documentation / learning efforts.

In reality, that's only one type of source. Some other sources might be actual GitHub repos. Others might be the documentation of PS tools and infrastructures. For example, how would we answer other questions that inform us about the current context/narrative like the ones below? Search engines can help find them, but to actually understand these 'sources,' we might need to read code and things like that:
1. What is currently 1) done well in, 2) done poorly but could be improved in, and 3) not done at all but should be done (i.e. new features that could greatly extend current capabilities) in PS' main documentation website: Pursuit? To do this, we could look through their issue tracker and their code.
2. What integrates with Pursuit (PS build tools, external websites like GitHub, etc.), how well does it integrate, and what are the benefits/limitations of those integrations and why?
3. How does the `purs docs` command work, what are its advantages and disadvantages, and how could improvements here greatly benefit the entire ecosystem? (For example, being able to link to other modules in some entity's documentation could greatly help)
4. What other learning materials already exist in the PS ecosystem?
    - who wrote them and how active are those people (would they want to be part of a potential documentation team? what are their incentives?)
    - who is their intended audience, what type of documentation are they (i.e. tutorial, how-to, reference, explanation)
5. What language backgrounds do new learners approaching PS have? What concepts do they already understand that can be used as scaffolds to help them learn new concepts faster? What baggage do they bring that must be addressed and clarified and when should that be done in their learning process? What kind of support do they need?
6. What kinds of projects are learners trying to build that makes using PS desirable? In other words, what are the 'gateway drug' projects that make people love PS and immediately understand its benefits over competing languages/ecosystems?

**Comment by JordanMartinez** [comment]
Regardless, let's still focus on finishing up what we currently have in the Sources folder. The above questions arise partly because of the research we've already done. I also realize that some of those questions can't be answered in a 1-2 week period, but they are helpful for guiding what we focus on.

**Comment by chexxor** [comment]
I really like your ideas of other sources. I'm intrigued by the idea of gathering facts from sources like GitHub projects' issue trackers or code-bases, and analyzing the content and scope of other educational materials in the PS ecosystem. I'd like to have this issue kept open until your ideas are acted on, either putting them in the Ideas-Storage.md file or increasing the scope and time allotment of the Gather Sources stage.

**Comment by JordanMartinez** [comment]
I think analyzing the GH projects goal will be my goal for next week (This week's was finishing all those sources). Then we can stick in the 1-2 week period (where next week is the 2nd week of that period)

**Comment by chexxor** [comment]
I'd like to find a way to close this issue to reduce the number of issues. If this is a discussion type issue, can we make some concrete to-do items from it? Briefly looking over this thread I see:

- ideas for more sources (but we are wrapping that up right now)
- discussion of outcome and purpose
- various questions/audiences that could be addressed by the documentation

I don't have any ideas of additional follow-up tasks we can create to replace this discussion issue?

**Comment by JordanMartinez** [comment]
We could always analyze more sources, but then we'd never get to writing the Context. The longer we wait, the more changes occur in the ecosystem that makes our analysis outdated in some respect.

IMO, this issue was actually closed in #40 because that issue addressed the questions I raised in my earlier comment (or at least most of them). We'll also just have to accept that our analysis will always be partial in some manner because "we could have analyzed Source X."
