### ISSUE TITLE
Possible copyright issues?

### ISSUE THREAD

**Issue by JordanMartinez** [chexxor/purescript-documentation-discussion#23]
Related to #21 regarding how we are analyzing sources. We are currently copying and pasting content into our files as it shows how we reached the conclusion/interpretation that we did. However, this might be breaking copyright in some situations. Maybe this wouldn't matter as much if this repo was private, but in a setting where anyone can see this, I wonder if the authors/commentors, etc. might notify GitHub about this repo and create problems for us.

Perhaps we should scrap the quoted content and just give our interpretations of a source in the file? It's not as ideal, but I don't know of a way around this issue.

**Comment by chexxor** [comment]
Good question. I've thought about it, too, in the past but I didn't take much action to learn deeply about it.
I think copyright has an exception for education use.

> Courts look at how the party claiming fair use is using the copyrighted work, and are more likely to find that nonprofit educational and noncommercial uses are fair.
> ...
> Under this factor, courts look at both the quantity and quality of the copyrighted material that was used.
> ...
> Here, courts review whether, and to what extent, the unlicensed use harms the existing or future market for the copyright owner’s original work.
> - https://www.copyright.gov/fair-use/more-info.html

What do you think?

**Comment by JordanMartinez** [comment]
Thanks for the link. 

Hmm... Well, in regards to the first one, we're doing this for noncommercial reasons and the purpose of our usage of the content is to more easily show 1) what specific part of some source we are interpreting and 2) how we reached that conclusion given what the source said. In some aspects, I did not include the full content of some source because it was not relevant to our focus/goal. Sometimes authors/commentors go on tangents and they are excluded. Thus, this seems to fall under the 'transformative' idea if I'm reading that article correctly

As for the second point, we're doing this as part of a factual technical focus, not a creative work. Person said X; we understand that to mean Y.

For the third, we are in some cases copying large portions of some sources (for example, blog posts and/or tweets) and just some parts from other sources (forum threads where one comment and its subcomments are relevant whereas the many other comments and their subcomments are irrelevant)

For the fourth, our content might show up in search engine results, rather than the actual site, which might draw traffic away from them and affect any ad revenue they might use. On another hand, we state very clearly what the purpose of this project is and, in the quoted parts of them, we link to those sites directly. So, it could be argued that we are actually redirecting people to those sites and might actually be increasing their traffic and ad revenue.

**Comment by chexxor** [comment]
I think we won't need to worry about copyright in this project. If a person contacts us and request us to remove, we can do that.

I don't know what action item we can take as part of this issue. I don't think we need to add a note to the root README about our thoughts on copyright issues... I suppose we could post a LICENSE file in the root of the project which describes our own copyrights.

The [purescript/documentation](https://github.com/purescript/documentation) project has a [CONTRIBUTORS.md](https://github.com/purescript/documentation/blob/master/CONTRIBUTORS.md) file which uses the [CC BY-NC-SA 3.0](https://creativecommons.org/licenses/by-nc-sa/3.0/deed) license. Perhaps we should simply adopt the same license for this project?

**Comment by JordanMartinez** [comment]
I'm fine with that license. We might want to clarify that the license applies strictly to our interpretations and other work, not necessarily the sources we're quoting.
Also, the CC BY-NC-SA has a [4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/). [here are the differences](https://creativecommons.org/share-your-work/licensing-considerations/version4/) Mind sticking with 4.0?

**Comment by chexxor** [comment]
@JordanMartinez I think we can close this issue if you add your name to the CONTRIBUTORS.md file.

**Comment by JordanMartinez** [comment]
Ok. How about I do that since I have more time and this is a minor issue? Then I'll close this.

**Comment by chexxor** [comment]
Sounds good.

**Comment by JordanMartinez** [comment]
Ok. I've added myself.
