### ISSUE TITLE
Top-level index of sources?

### ISSUE THREAD

**Issue by chexxor** [chexxor/purescript-documentation-discussion#24]
When I find a new source I'd like to analyze, I'd like to check it against a list of sources we've already analyzed in this project. Perhaps we can have a top-level index of the sources we've analyzed in this project? We can put a link from that source to the file in file-name in this project where the analysis is occurring. I'd prefer to use a loose mapping from source to file-name in this project, because I expect we'll be moving files around and changing the naming scheme.

**Comment by JordanMartinez** [comment]
I'm having a bit of trouble understanding what your idea is. It sounds like what you are proposing is a way to make it easy for either of us to determine whether a source is already included in this project and your approach for doing that is a file whose content acts like a `Map Source FileName` type. Should we ever move the files around or rename them, we can update the source's file name.

It also sounds like that index file's content would look like this:

| Source | File Name |
| - | - |
| Comment URL | Hitchhiker's Guide to Elm |
| Comment URL | some other file name |

I don't think that's a bad idea. However, my concern is keeping that index file in-sync. Regardless, we should update the workflow documentation to insure we're on the same page.

**Comment by chexxor** [comment]
I'll make a PR tomorrow. 👍
