### ISSUE TITLE
Include Elm PS Differences document

### ISSUE THREAD

**Issue by JordanMartinez** [chexxor/purescript-documentation-discussion#25]
I noticed that another person starred this repo and I saw they had an ['intro to PS' slides/talk](https://github.com/sassela/talk-intro-to-purescript). On the final slide, where they listed other sources, they linked to Justin Woo's outdated [Differences of Purescript from Elm](https://gist.github.com/justinwoo/0118be3e4a0d7394a99debbde2515f9b) page, which might help people transition from Elm to PureScript

**Comment by chexxor** [comment]
Are you thinking this would be a source we analyze? Or a thing that would be useful when we are developing goals and strategies such?

**Comment by JordanMartinez** [comment]
Definitely not something we'll analyze. It's for developing goals and strategies.

One such idea is compiling a list of learning resources for people coming from some specific background. The above could be a sort of quick overview of their differences. I'm not sure if it's the best thing out there for that purpose (e.g. itmight be outdated, not as coherent as other resources, etc.). Still, I'd like to remember it for later, just in case.

**Comment by chexxor** [comment]
It seems like it would be worth creating a document like "Ideas-Storage" but for useful, good resources. They could be resources for learning PureScript or for documentation sites we'd like to pull ideas from, for example.

**Comment by JordanMartinez** [comment]
Pretty much. In the GTD methodology, such files act like a crude sort of 'filing cabinet.' Technically, we could use issues for the same thing, but that might lead to issue spam if we have a lot opened.

**Comment by chexxor** [comment]
I'd prefer to reserve issues for concrete, workable items. An issue's work item can be to gather feedback before/while adding an idea to a 'filing cabinet' file. I say that because I look through all the issues here when starting to contribute here, and having issues which aren't workable works against this workflow.

**Comment by JordanMartinez** [comment]
Ok, sounds good to me. We should document this in the project's ReadMe.

**Comment by chexxor** [comment]
@JordanMartinez I see you added this link to the "Learning-Resources-Analysis" file: https://github.com/chexxor/purescript-documentation-discussion/commit/9b9f806c60419efe1ac1a5e3c9bae86b7fdb6672
Can we close this issue?

**Comment by JordanMartinez** [comment]
Oh! Whoops! Yeah, we can close this.
