### ISSUE TITLE
Issue Labels to use for tracking issues/content

### ISSUE THREAD

**Issue by JordanMartinez** [chexxor/purescript-documentation-discussion#3]
Related to #1, but how should we use Issue Labels to categorize the issues?

**Comment by chexxor** [comment]
I think that's a function of the issues that we expect to exist. I am not sure what the issues we create will be about, at this time. I think we can approach this issue after we've created many other issues.

Do you have any ideas about how we can use issues here? I imagine we'd use issues for the purpose of gathering discussion or for tracking concrete work items.

**Comment by JordanMartinez** [comment]
> I think that's a function of the issues that we expect to exist. I am not sure what the issues we create will be about, at this time. I think we can approach this issue after we've created many other issues.

Sounds good. Perhaps we should use this issue to further discuss that once we have more issues opened?

> Do you have any ideas about how we can use issues here? I imagine we'd use issues for the purpose of gathering discussion or for tracking concrete work items.

Let's treat it like a regular coding project. Open an issue to indicate some task that needs to be done. When you're ready to start working on it, assign it to yourself to indicate that you're working on it. If it's not assigned, then we assume either of us can work on it. Once we merge it into master, we can mark it as closed by a specific commit hash. 
Does that approach sound good to you?

**Comment by JordanMartinez** [comment]
We haven't discussed this issue further since it was created. I don't foresee us doing anything like this in the future, at least for now, so I'm going to close it to reduce the number of issues we have.
