### ISSUE TITLE
No longer analyze 'Outsider's Guide to FP' book

### ISSUE THREAD

**Issue by JordanMartinez** [chexxor/purescript-documentation-discussion#34]
I thought the preface of this book was worthwhile, but I think we've already covered the points the author makes elsewhere. So, I'm going to say let's not analyze this source.

Rather, let's include it as a possible learning resource for people. While I haven't read it, I think it's likely one of the best JS -> Elm -> PS resources out there.

**Comment by chexxor** [comment]
Yeah, I looked through the preface/intro a few times and I agree with what you say.

**Comment by chexxor** [comment]
Resolved in https://github.com/chexxor/purescript-documentation-discussion/commit/97840e5d0937103cb6084c1424dd8ff5b91e20a8
