### ISSUE TITLE
Defining source formatting

### ISSUE THREAD

**Issue by JordanMartinez** [chexxor/purescript-documentation-discussion#6]
Just to clarify, here's how I'm structuring my analysis/interpretation of things:

## Source: source name

[link to the source]()

### Opening Thread

(no link included here since the source link is this link)

> Relevant info stated in that opening comment

- my interpretation of that info

> Relevant info stated in that opening comment

- my interpretation of that info

### Comment in that thread

[link to that comment]()
[if the same person made another comment immediately after the previous one, then I'll include it here, too]()

> Relevant info stated in that comment

- my interpretation of that info

<hr>

I think you've structured your content similar to what I have above, likely as a way of trying to follow the format I've started here. However, it's different in one way.
- Rather than using 2 "#" characters for h2 top-level sources and 3 "#" characters for h3 comments/ideas in those sources, it seems you are using 3 "#" characters for h3 top-level sources.

First, does this approach to analyzing the sources work for you? Second, are you ok with using the format I am using above? 

Also, with what we have so far, what issues have you come across with this current formatting?

**Comment by chexxor** [comment]
I'm glad you opened an issue for this. My understanding of your format was pretty close, but I was a bit off. I changed it to more closely match this style soon after, I think.

The one question I still have is where to put links to comments on a bigger thread. I put them in the quote itself, because I think it's easier to read and matches quotation citation styles in magazines where they quote celebrities.

Feel free to take a look at a few of the analyses I've done, which would be the ones you didn't do, and let me know if I'm missing anything important.

**Comment by JordanMartinez** [comment]
> Feel free to take a look at a few of the analyses I've done, which would be the ones you didn't do, and let me know if I'm missing anything important.

Ok, I will.

> The one question I still have is where to put links to comments on a bigger thread. I put them in the quote itself, because I think it's easier to read and matches quotation citation styles in magazines where they quote celebrities.

That's a good point. I actually didn't specify above what the formatting was that I used for that. It's now been updated.

In short, I do this:

### Comment

[link to that comment]()
[if the same person made another comment immediately after the previous one, then I'll include it here, too]()

> Relevant info in comment

- my interpretation/analysis of comment

**Comment by JordanMartinez** [comment]
Feel free to review my interpretation/analysis and modify them or add your own

**Comment by chexxor** [comment]
> Feel free to review my interpretation/analysis and modify them or add your own

I like your analysis quite a bit. I'm very impressed.

After looking through sources like this, I'm excited for the later steps.

**Comment by JordanMartinez** [comment]
:-D

**Comment by chexxor** [comment]
We can keep this open for reference until we're done with the sources stage.

**Comment by JordanMartinez** [comment]
I've added this to the ReadMe of the `sources and interpretation` folder
