### ISSUE TITLE
Defining workflow

### ISSUE THREAD

**Issue by JordanMartinez** [chexxor/purescript-documentation-discussion#7]
I noticed after finishing my analysis/interpretation of 'How do we avoid ecosystem incoherence,' that you had also done some work on that. This made merging my work into `master` more difficulty.

What should we do to insure that we're not working on the same things? Perhaps we should using the Slack channel for more instantaneous communication as opposed to issues to notify one another what we're currently working on?

**Comment by chexxor** [comment]
When I look ahead, it looks likely that multiple people will be working on the same file at the same time, so it would be valuable to mitigate this problem now.

It would be nice to avoid PRs at an early stage like this, which means making commits directly to master. If doing that, then the easiest way to avoid merge conflicts is to make the time between editing and committing relatively small. This means many small commits, which I think should be ok. What do you think of this? Does this clash with your workflow?

**Comment by chexxor** [comment]
When working on something large, perhaps it's best to make a branch for that and working in that branch. I guess having a branch would make merging easier, but it's just a guess. Additionally, before starting work on that something large, an issue can be created which represents your "lock" on that content. I'm not sure what large content will be managed this way, so this could be a poor plan. It's an idea, anyway.

**Comment by JordanMartinez** [comment]
> It would be nice to avoid PRs at an early stage like this, which means making commits directly to master.

I agree. PRs will definitely slow this down and they are unnecessary.

> When I look ahead, it looks likely that multiple people will be working on the same file at the same time, so it would be valuable to mitigate this problem now.

Our goal is to analyze sources right now and not analyze the same source at the same time. Also, we want to be able to push to master without any bottlenecks. I like the atomic commits, but I also realize that this is only one possible solution to the merge conflict issue we're experiencing, so there might be better ways of handling it.

We seem to have a sort of 5-step process
- someone 'locks' the source of data as a way to indicate they are doing it
- someone analyzes some source of data and writes their interpretation
- someone pushes that to master all at once or atomically and frequently
- someone 'unlocks' that source of data to show they are done
- the other person might review it and add their own thoughts/comments
- everything is integrated into one location

Perhaps each source could be its own file under its own name (temporarily). That would definitely prevent merge conflicts and we could later integrate it into one location (either a single file or move all files into one folder)

> Additionally, before starting work on that something large, an issue can be created which represents your "lock" on that content. I'm not sure what large content will be managed this way, so this could be a poor plan. It's an idea, anyway.

It's an idea that will work for now. Let's do that and self-assign ourselves to that issue as a way to indicate a lock and close it when we're finished. That's what I've done for #4 and #5 :-D

At a later time when we've analyzed/interpreted more data, we can then decide to review the others work and store all the files inside one folder.

How does that sound?

**Comment by chexxor** [comment]
Yeah, separate files will work well. It's a good proposal. 👍

**Comment by JordanMartinez** [comment]
Ok, we'll go with that. Will we still use the issue-as-a-lock-mechanism?

**Comment by chexxor** [comment]
Yeah, we can try it. We can use the assignee as the lock owner.

**Comment by JordanMartinez** [comment]
Since we're going the separate-file-per-source route, let's also set up 4 folders:
- Done (these sources are done)
- Ready for Jordan (Alex has finished his initial work and now Jordan can review them)
- Ready for Alex (Jordan has finished his initial work and now Alex can review them)
- Not Yet Analyzed (these are not yet analzyed sources or are the current place where someone is doing their initial work. If we ever want to add another source to investigate, we can create a file and put it into this folder)

**Comment by chexxor** [comment]
Shall we close this one for now? I think we have a pretty good workflow going right now, and we documented it in the root README, so we have a place to add clarification if thats needed.

**Comment by JordanMartinez** [comment]
Yeah. Let's close it.
