### ISSUE TITLE
Discontinuing my contributions to this project

### ISSUE THREAD

**Issue by JordanMartinez** [chexxor/purescript-documentation-discussion#73]
I've decided to discontinue my contributions to this project.

The first reason is personal and can't be resolved. The remaining reasons are largely problems that could be resolved.

**Opportunity cost:** I spent a large number of hours contributing to this project. As a result, I did not spend that same time pursuing other goals (as mentioned in #39) that I hoped to complete by the beginning of May. Due to failing to meet those goals, I'm saying 'no' to this project.

**Loss of direction and momentum:** originally, our goal was to produce something within a few weeks (a month at most). That was the original reason I contributed as much as I did. I believed this project would act as a "call to action," a point around which the community could rally and something that would guide community contributions. Over time, it started to feel like we lost direction when it came to #50. What should be said? How should it be said? What is and isn't included in this document? Who is the intended audience of the document? 
I remember thinking to myself and explaining to friends and family, "We didn't finish it this week, but I'm sure it'll be done in about two weeks." Unfortunately, that conversation happened every 2-3 weeks. The weeks passed and the goal was not met. Over time, I stopped wanting to contribute to this project and eventually started to dread it. 

I believe the "problem" here is composed of a few smaller problems:
- a lack of a mutual understanding of and experience with my modified GTD methodology. There were some things I did not explain because I thought they'd be self-evident. There were other things in that methodology that I realized need more clarification or revision.
- a lack of a mutual understanding of and agreement on terms we use and their definition, so that we're "on the same page" when having conversations.
- a lack of a mutual understanding of and agreement on the Context/Narrative document: target audience, scope, length, content, etc.

**The longer this takes, the more outdated it is**: It's been ~4 months since we started this project. As we did our research, we came across "problems" in the documentation and thought of ways they could be fixed. However, due to #50 taking so long, some of those problems got fixed, making those sections outdated. For example, the OOM bower issue that stopped libraries like Halogen from uploading their docs to Pursuit got fixed. The compiler errors that some/many consider to be poor are become better with the new CST parser. 

The "problem" here might not be considered a problem by all. While the Context/Narrative document we write might not contain the most accurate info, it's still better than nothing and more up-to-date than other **older** posts to which we can refer. 
I think this problem bothers me only because we weren't able to complete #50 faster as that was going to be the end of my contribution to this project (see #39). So, when I saw parts of the Context/Narrative document becoming outdated, it reminded me that I didn't finish this yet.

**Comment by chexxor** [comment]
Thanks for notifying about this! It'll be lonely here without you, but I highly value this project so I'll try to finish it. I know for sure this project wouldn't have happened without your help to kick-start it! Thanks so much, and I hope you see success in your other projects!

**Comment by JordanMartinez** [comment]
Thanks! And I wish you well on this project. Perhaps others would like to contribute towards it?
