### ISSUE TITLE
Separate "Sources" into separate files

### ISSUE THREAD

**Issue by chexxor** [chexxor/purescript-documentation-discussion#8]
As discussed in https://github.com/chexxor/purescript-documentation-discussion/issues/7#issuecomment-453790086

We should split the files comprising the "Sources" stage into multiple smaller files to reduce merge conflicts while collaborating.

**Comment by chexxor** [comment]
@JordanMartinez, let me know when you've committed any work-in-progress related to the "Sources" step, then someone can split it up into smaller files. I'll hold off on work on that file until this issue is complete.

**Comment by JordanMartinez** [comment]
I'm done. please do this as soon as possible.

**Comment by chexxor** [comment]
I've created subdirectories as you suggested in the "Defining workflow" issue.
I've moved all sources out of the 01-Sources-and-Interpretation.md file and into the 01-Sources-and-Interpretation subdirectories.
This issue is complete, then.

**Comment by JordanMartinez** [comment]
Great! Let's close this then.
